### PR TITLE
clean up static resources and fix console errors

### PR DESCRIPTION
**Pull request by merlinran**
This PR does the following without behavioural changes, to lay a foundation for further frontend changes:
1. move js libraries to `js/lib`;
2. remove unused js and css library files;
3. add missing js map file and image files;
4. re-format HTML to have consistent indentation and easily recognizable blocks;
5. call `getRobotData()` only after `map` is initialized.

Better to be review with "Hide whitespace" ticked.

### CODE REVIEW

**Comment by tlalexander** [comment]
Very exciting! I will take a look at this when I can. I am working on PCB design work so there won't be any collisions with your changes for some time. Still need to read your email. Thanks for working on this!

**Comment by tlalexander** [comment]
Looking at this now. I am also learning how to review pull requests but I installed the github CLI so I can review these locally.

First thing I noticed is server/*.rdb in the .gitignore. We do need to be able to commit the database from time to time so that the code works. We have no code to initialize the database (one of many TODOs) so it will crash if the database doesn't reflect current code. It looks like since the file is already committed github will track changes even though it matches the ignore, but to avoid confusion maybe that part should be removed from the ignore file.

**Comment by tlalexander** [comment]
I'll change the gitignore later and merge this now.

**Comment by merlinran** [comment]
> Looking at this now. I am also learning how to review pull requests but I installed the github CLI so I can review these locally.
> 

Yeah trying out PRs from forked repo requires extra effort. I would have to `git remote add merlin https://github.com/merlinran/acorn-precision-farming-rover.git`, then `git checkout merlin/<branch>`, and probably create new branches off them to add amendments.

Alternatively, you can add me as [an outside collaborator to the repo](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/adding-outside-collaborators-to-repositories-in-your-organization#adding-outside-collaborators-to-a-repository) so I can create new branches in `Twisted-Fields/acorn-precision-farming-rover` repo directly.

> First thing I noticed is server/*.rdb in the .gitignore. We do need to be able to commit the database from time to time so that the code works. We have no code to initialize the database (one of many TODOs) so it will crash if the database doesn't reflect current code. It looks like since the file is already committed github will track changes even though it matches the ignore, but to avoid confusion maybe that part should be removed from the ignore file.

Yeah sorry I also realized that later and reverted it back in https://github.com/Twisted-Fields/acorn-precision-farming-rover/pull/7 .

**Pull request merged**
